/**
 * Writes the token CSS from the palette file. Run by `npm run tokens:build`,
 * which predev and prebuild both call, and checked by a test that reruns this
 * and diffs — otherwise someone edits a colour, forgets the build, and
 * everything still compiles with stale ones.
 */
import { writeFileSync } from "node:fs"
import { resolve } from "node:path"
import { DEFAULT_PALETTE, palettes, ROLES } from "../src/tokens/palette.ts"

/**
 * Repo-relative, and left that way on purpose: the test importing this runs
 * under Vitest, which serves modules over http and hands import.meta.url a URL
 * no fs call will accept. So the path is resolved by each caller instead — from
 * this file for the CLI below, and from the Vitest root for the test.
 */
export const OUTPUT = "src/tokens/tokens.css"

export function buildTokenCss(): string {
  return [BANNER, ...MODE_RULES, ...Object.keys(palettes).map(paletteRule)].join("\n") + "\n"
}

function paletteRule(name: string): string {
  // The default palette also answers to bare :root, so a page that never sets
  // data-theme still has every token rather than none.
  const selector = name === DEFAULT_PALETTE ? `:root,\n[data-theme="${name}"]` : `[data-theme="${name}"]`
  const palette = palettes[name as keyof typeof palettes]
  const lines = ROLES.map((role) => `  --${role}: light-dark(${palette[role].light}, ${palette[role].dark});`)

  return `\n${selector} {\n${lines.join("\n")}\n}`
}

const BANNER = "/* Generated by scripts/build-tokens.mts from src/tokens/palette.ts. Do not edit. */"

// Mode rides on the browser's own color-scheme rather than a second attribute,
// because color-scheme inherits and an attribute selector does not — see §4.1.
// The :not() is load-bearing: as a bare :root this has the same specificity as
// the light rule below, so which one won would depend on stylesheet order.
const MODE_RULES = [
  `:root:not([data-mode]) { color-scheme: light dark; }`,
  `[data-mode="light"] { color-scheme: light; }`,
  `[data-mode="dark"], .dark { color-scheme: dark; }`,
]

if (import.meta.filename === process.argv[1]) {
  const path = resolve(import.meta.dirname, "..", OUTPUT)
  writeFileSync(path, buildTokenCss())
  console.log(`wrote ${path}`)
}
